AWSTemplateFormatVersion: 2010-09-09
Description: This template will create Amazon Location Service place index, tracker, and geofence collection resources, and an Amazon Cognito identity pool and associated IAM role and policy. The policy will restrict use of the tracker and place index resources to the specified domain. 
Parameters:
  ResourceNamePrefix:
    Type: String
    Description: This prefix will be used for place index, tracker, geofence collection, and identity pool resources
  
Resources:
  Tracker:
    Type: 'AWS::Location::Tracker'
    Properties:
      TrackerName: !Sub '${ResourceNamePrefix}Tracker'
      PricingPlan: RequestBasedUsage
  GeofenceCollection:
    Type: 'AWS::Location::GeofenceCollection'
    Properties:
      CollectionName: !Sub '${ResourceNamePrefix}GeofenceCollection'
      PricingPlan: RequestBasedUsage
  Index:
    Type: 'AWS::Location::PlaceIndex'
    Properties:
      DataSource: Esri
      DataSourceConfiguration:
        IntendedUse: SingleUse
      IndexName: !Sub '${ResourceNamePrefix}Index'
      PricingPlan: RequestBasedUsage
  TrackerConsumer:
    Type: 'AWS::Location::TrackerConsumer'
    Properties:
      ConsumerArn: !GetAtt GeofenceCollection.Arn
      TrackerName: !Sub '${Tracker}'
  IdentityPool:
    Type: 'AWS::Cognito::IdentityPool'
    Properties:
      IdentityPoolName: !Sub '${ResourceNamePrefix}Pool'
      AllowUnauthenticatedIdentities: true
  CognitoUnAuthorizedRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: !Sub '${ResourceNamePrefix}UnauthorizedPolicy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SearchPlaceIndexOnly
                Effect: Allow
                Action:
                  - 'geo:SearchPlaceIndexForText'
                Resource: !Sub 'arn:${AWS::Partition}:geo:${AWS::Region}:${AWS::AccountId}:place-index/${Index}' 
              - Sid: TrackerOnly
                Effect: Allow
                Action:
                  - 'geo:BatchUpdateDevicePosition'
                Resource: !Sub 'arn:${AWS::Partition}:geo:${AWS::Region}:${AWS::AccountId}:tracker/${Tracker}' 
              
  IdentityPoolRoleMapping:
    Type: 'AWS::Cognito::IdentityPoolRoleAttachment'
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn
Outputs:
  IdentityPoolID:
    Description: The Cognito identity pool ID 
    Value: !Ref IdentityPool
  GeofenceCollectionName:
    Description: The geofence collection resource name
    Value: !Ref GeofenceCollection  
  TrackerName:
    Description: The tracker resource name
    Value: !Ref Tracker  
  PlaceIndexName:
    Description: The Place Index resource name
    Value: !Ref Index
